"""Configuration + on-disk paths for learnlance.

Everything lives under ~/.learnlance (override with LEARNLANCE_HOME).
No third-party dependencies anywhere in this package on purpose: the hook must
run reliably in whatever environment Claude Code launches it in.

Per-project graphs are stored under ~/.learnlance/projects/<slug>/graph.json.
A registry at ~/.learnlance/projects.json tracks all known projects.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path

HOME = Path(os.environ.get("LEARNLANCE_HOME", str(Path.home() / ".learnlance")))
CONFIG_PATH = HOME / "config.json"
GRAPH_PATH = HOME / "graph.json"  # legacy single-graph (migrated on first use)
HTML_PATH = HOME / "graph.html"
STATE_PATH = HOME / "state.json"
INSIGHTS_DIR = HOME / "insights"
WORK_DIR = HOME / "work"
LOG_PATH = HOME / "learnlance.log"
PROJECTS_DIR = HOME / "projects"
PROJECTS_REGISTRY = HOME / "projects.json"
# Edits captured mid-session by harnesses that report one tool call at a time
# (Kiro, Cursor, …). Drained when the session's Stop hook fires.
PENDING_DIR = HOME / "pending"

DEFAULTS = {
    "enabled": True,
    # Insights are generated by shelling out to an LLM CLI you're already logged
    # into (NO API key needed). Any CLI that reads a prompt on stdin works.
    #   "" => auto-detect: claude, gemini, copilot, cursor-agent, ollama
    #   e.g. "ollama run llama3", "gemini -p"
    "llm_cmd": "",
    "claude_bin": "",  # legacy: explicit path to `claude`; llm_cmd supersedes it
    "cli_model": "",  # optional model alias for the CLI (e.g. "haiku"); "" => default
    "max_topics_per_turn": 5,
    "background": True,  # run the work detached so Claude Code stays snappy
    "min_chars": 40,  # skip trivial edits (renames, one-liners) to save calls
    "max_input_chars": 14000,  # cap the code we send per turn
}

# Env flag set on any `claude` process we spawn, so the Stop hook it fires can
# recognize it's a learnlance-triggered call and bail instead of recursing.
REENTRY_FLAG = "LEARNLANCE_ACTIVE"


def ensure_home() -> None:
    HOME.mkdir(parents=True, exist_ok=True)
    INSIGHTS_DIR.mkdir(parents=True, exist_ok=True)
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    PENDING_DIR.mkdir(parents=True, exist_ok=True)


def load_config() -> dict:
    cfg = dict(DEFAULTS)
    if CONFIG_PATH.exists():
        try:
            cfg.update(json.loads(CONFIG_PATH.read_text(encoding="utf-8")))
        except Exception:
            pass
    return cfg


def save_config(cfg: dict) -> None:
    ensure_home()
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2), encoding="utf-8")


def log(msg: str) -> None:
    try:
        ensure_home()
        with LOG_PATH.open("a", encoding="utf-8") as fh:
            fh.write(msg.rstrip() + "\n")
    except Exception:
        pass


# --------------------------------------------------------------------------- #
# Per-project graph paths + registry
# --------------------------------------------------------------------------- #

def canonical_project_path(cwd: str) -> str:
    """Normalize a project path so one project always maps to one identity.

    `normcase` matters: on Windows `c:\\proj` and `C:\\proj` are the same
    directory, and without folding the case they'd hash to two different slugs —
    silently splitting a project's knowledge graph in half. It's a no-op on POSIX,
    where case genuinely is significant.
    """
    return os.path.normcase(os.path.normpath(os.path.abspath(cwd)))


def _project_slug(cwd: str) -> str:
    """Create a filesystem-safe slug from a project path.

    Uses the directory basename + a short hash of the full path to avoid
    collisions between projects with the same folder name.
    """
    cwd = canonical_project_path(cwd)
    basename = re.sub(r"[^a-z0-9]+", "-", os.path.basename(cwd).lower()).strip("-") or "project"
    short_hash = hashlib.md5(cwd.encode()).hexdigest()[:6]
    return f"{basename}-{short_hash}"


def project_dir(cwd: str) -> Path:
    """Return the per-project storage directory for the given workspace."""
    return PROJECTS_DIR / _project_slug(cwd)


def project_graph_path(cwd: str) -> Path:
    """Return the graph.json path for a specific project."""
    return project_dir(cwd) / "graph.json"


def project_html_path(cwd: str) -> Path:
    """Return the graph.html path for a specific project."""
    return project_dir(cwd) / "graph.html"


def load_projects_registry() -> dict:
    """Load the registry of all known projects.

    Format: { "<slug>": {"path": "/abs/path", "name": "basename", "last_seen": "..."} }
    """
    if PROJECTS_REGISTRY.exists():
        try:
            return json.loads(PROJECTS_REGISTRY.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def save_projects_registry(registry: dict) -> None:
    ensure_home()
    PROJECTS_REGISTRY.write_text(json.dumps(registry, indent=2), encoding="utf-8")


def register_project(cwd: str) -> str:
    """Register a project in the registry. Returns the project slug."""
    import datetime as _dt
    # Display the path as the OS gave it, but key it off the canonical form.
    cwd = os.path.normpath(os.path.abspath(cwd))
    slug = _project_slug(cwd)
    registry = load_projects_registry()
    entry = registry.get(slug, {})
    entry["path"] = cwd
    entry["name"] = os.path.basename(cwd)
    entry["last_seen"] = _dt.datetime.now().isoformat(timespec="seconds")
    registry[slug] = entry
    save_projects_registry(registry)
    # Ensure the project directory exists
    pdir = project_dir(cwd)
    pdir.mkdir(parents=True, exist_ok=True)
    return slug


def migrate_legacy_graph(cwd: str) -> bool:
    """If a legacy single graph.json exists and the project has no graph yet,
    move it to the project's directory. Returns True if migration happened."""
    if not GRAPH_PATH.exists():
        return False
    target = project_graph_path(cwd)
    if target.exists():
        return False
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        # Copy (not move) so we don't break anything if multiple projects shared it.
        import shutil
        shutil.copy2(GRAPH_PATH, target)
        # Rename the legacy file so migration doesn't repeat.
        GRAPH_PATH.rename(GRAPH_PATH.with_suffix(".json.migrated"))
        return True
    except Exception:
        return False
